export type InstagramBackground = "encounter" | "midnight" | "warmth";

export type InstagramPost = {
  day: number;
  weekday: string;
  theme: string;
  purpose: string;
  text: string;
  caption: string;
  background: InstagramBackground;
};

export const INSTAGRAM_POSTS: InstagramPost[] = [
  {
    day: 1,
    weekday: "Montag",
    theme: "Haltung",
    purpose: "Choice-Gedanke",
    text: "Vielleicht brauchst du nicht mehr Auswahl.\n\nVielleicht brauchst du jemanden, der bleibt.",
    caption: "Mehr Auswahl macht nicht automatisch klarer. Manchmal beginnt Nähe genau dort, wo wir aufhören, weiterzusuchen.\n\n#choice #datingmitabsicht #echteverbindung",
    background: "encounter",
  },
  {
    day: 2,
    weekday: "Dienstag",
    theme: "Community",
    purpose: "Frage an die Community",
    text: "Woran merkst du, dass ein Gespräch wirklich leicht wird?",
    caption: "Ist es die Zeit, die plötzlich schneller vergeht? Oder das Gefühl, nichts beweisen zu müssen? Schreib es uns.\n\n#choicefrage #kennenlernen #dating",
    background: "midnight",
  },
  {
    day: 3,
    weekday: "Mittwoch",
    theme: "Nähe",
    purpose: "Leiser Gedanke",
    text: "Die schönsten Gespräche beginnen selten mit der perfekten ersten Nachricht.",
    caption: "Sie beginnen mit ehrlicher Neugier.\n\n#choice #ehrlichkennenlernen #nähe",
    background: "warmth",
  },
  {
    day: 4,
    weekday: "Donnerstag",
    theme: "Klarheit",
    purpose: "Dating-Realität",
    text: "Interesse fühlt sich nicht wie Rätselraten an.",
    caption: "Du darfst Klarheit erwarten. Nicht irgendwann, sondern auch schon beim Kennenlernen.\n\n#klarheit #datinggedanken #choice",
    background: "encounter",
  },
  {
    day: 5,
    weekday: "Freitag",
    theme: "Mut",
    purpose: "Wochenend-Impuls",
    text: "Vielleicht ist heute ein guter Tag, um nicht nur ‚irgendwann‘ zu sagen.",
    caption: "Eine ehrliche Nachricht. Ein Kaffee. Ein kleiner Schritt aus dem Vielleicht.\n\n#choice #freitagsgefühl #mutzurnähe",
    background: "warmth",
  },
  {
    day: 6,
    weekday: "Samstag",
    theme: "Leichtigkeit",
    purpose: "Speicherbarer Satz",
    text: "Das beste Date ist nicht perfekt. Es fühlt sich nur echt an.",
    caption: "Kein Drehbuch. Kein Eindruck, den du spielen musst. Nur zwei Menschen, die schauen, was entsteht.\n\n#dateidee #choice #echtheit",
    background: "midnight",
  },
  {
    day: 7,
    weekday: "Sonntag",
    theme: "Reflexion",
    purpose: "Wochenabschluss",
    text: "Du musst niemanden überzeugen, der dich wirklich kennenlernen möchte.",
    caption: "Für den ruhigen Sonntagabend.\n\n#sonntagsgedanke #selbstwert #choice",
    background: "encounter",
  },
  {
    day: 8,
    weekday: "Montag",
    theme: "Haltung",
    purpose: "Choice-Gedanke",
    text: "Ein Match ist kein Versprechen. Aber es darf eine echte Chance sein.",
    caption: "Nicht hundert Möglichkeiten gleichzeitig. Eine Begegnung, der du wirklich Aufmerksamkeit gibst.\n\n#choice #onematch #bewusstdaten",
    background: "midnight",
  },
  {
    day: 9,
    weekday: "Dienstag",
    theme: "Community",
    purpose: "Frage an die Community",
    text: "Was ist dir wichtiger: sofortige Chemie oder langsam wachsendes Vertrauen?",
    caption: "Es gibt keine falsche Antwort. Wir sind neugierig auf deine.\n\n#choicefrage #chemie #vertrauen",
    background: "warmth",
  },
  {
    day: 10,
    weekday: "Mittwoch",
    theme: "Nähe",
    purpose: "Leiser Gedanke",
    text: "Manche Menschen wirken nicht laut. Nur lange nach.",
    caption: "Vielleicht ist genau das die Art von Verbindung, die bleibt.\n\n#choice #verbindung #kennenlernen",
    background: "encounter",
  },
  {
    day: 11,
    weekday: "Donnerstag",
    theme: "Klarheit",
    purpose: "Dating-Realität",
    text: "Du darfst jemanden mögen und trotzdem merken, dass es nicht passt.",
    caption: "Ehrlichkeit macht eine Begegnung nicht weniger wertvoll. Sie macht sie fair.\n\n#datingklarheit #choice #fairplay",
    background: "midnight",
  },
  {
    day: 12,
    weekday: "Freitag",
    theme: "Mut",
    purpose: "Wochenend-Impuls",
    text: "Frag nicht nur, was jemand macht. Frag, was ihn lebendig macht.",
    caption: "Eine Frage für dein nächstes echtes Gespräch.\n\n#gesprächsimpuls #choice #deepquestions",
    background: "warmth",
  },
  {
    day: 13,
    weekday: "Samstag",
    theme: "Leichtigkeit",
    purpose: "Speicherbarer Satz",
    text: "Grüne Flagge: Du kannst du selbst sein, ohne dich kleiner zu machen.",
    caption: "Welche Green Flag ist für dich unverzichtbar?\n\n#greenflags #choice #gesundedynamik",
    background: "encounter",
  },
  {
    day: 14,
    weekday: "Sonntag",
    theme: "Reflexion",
    purpose: "Wochenabschluss",
    text: "Vielleicht war es kein Scheitern. Vielleicht war es Klarheit.",
    caption: "Nicht jede Begegnung muss bleiben, um etwas zu bedeuten.\n\n#sonntagsgedanke #loslassen #choice",
    background: "midnight",
  },
  {
    day: 15,
    weekday: "Montag",
    theme: "Haltung",
    purpose: "Choice-Gedanke",
    text: "Weniger swipen. Mehr herausfinden, wer wirklich vor dir ist.",
    caption: "Choice gibt einer Begegnung Zeit, bevor die nächste beginnt.\n\n#choice #datingslowdown #onematch",
    background: "encounter",
  },
  {
    day: 16,
    weekday: "Dienstag",
    theme: "Community",
    purpose: "Frage an die Community",
    text: "Welche kleine Geste sagt für dich mehr als große Worte?",
    caption: "Eine Nachricht zur richtigen Zeit? Zuhören? Sich etwas Kleines merken?\n\n#choicefrage #liebeimdetail #dating",
    background: "warmth",
  },
  {
    day: 17,
    weekday: "Mittwoch",
    theme: "Nähe",
    purpose: "Leiser Gedanke",
    text: "Nähe beginnt dort, wo du nicht mehr beeindrucken musst.",
    caption: "Sondern einfach ankommen darfst.\n\n#nähe #choice #echteverbindung",
    background: "midnight",
  },
  {
    day: 18,
    weekday: "Donnerstag",
    theme: "Klarheit",
    purpose: "Dating-Realität",
    text: "Konstanz ist romantischer als gemischte Signale.",
    caption: "Interesse darf sich ruhig, klar und verlässlich anfühlen.\n\n#klarheit #datinggedanken #choice",
    background: "encounter",
  },
  {
    day: 19,
    weekday: "Freitag",
    theme: "Mut",
    purpose: "Wochenend-Impuls",
    text: "Sag heute etwas, das du sonst nur denkst.",
    caption: "Ehrlich. Freundlich. Ohne Taktik.\n\n#mut #choice #ehrlichkommunizieren",
    background: "warmth",
  },
  {
    day: 20,
    weekday: "Samstag",
    theme: "Leichtigkeit",
    purpose: "Speicherbarer Satz",
    text: "Ein gutes Zeichen: Ihr könnt zusammen lachen, ohne jemanden auszulachen.",
    caption: "Leichtigkeit und Respekt passen ziemlich gut zusammen.\n\n#greenflag #choice #zusammenlachen",
    background: "midnight",
  },
  {
    day: 21,
    weekday: "Sonntag",
    theme: "Reflexion",
    purpose: "Wochenabschluss",
    text: "Du bist nicht zu viel für jemanden, der dich nicht nur halb will.",
    caption: "Eine Erinnerung für später.\n\n#selbstwert #sonntagsgedanke #choice",
    background: "encounter",
  },
  {
    day: 22,
    weekday: "Montag",
    theme: "Haltung",
    purpose: "Choice-Gedanke",
    text: "Die nächste Person ist nicht immer die bessere Möglichkeit.",
    caption: "Manchmal ist sie nur die nächste. Aufmerksamkeit verändert, wie wir einander begegnen.\n\n#choice #bewusstdaten #wenigeristmehr",
    background: "midnight",
  },
  {
    day: 23,
    weekday: "Dienstag",
    theme: "Community",
    purpose: "Frage an die Community",
    text: "Welche Frage würdest du gern schon beim ersten Date stellen?",
    caption: "Nicht die höfliche. Die ehrliche.\n\n#choicefrage #erstesdate #kennenlernen",
    background: "warmth",
  },
  {
    day: 24,
    weekday: "Mittwoch",
    theme: "Nähe",
    purpose: "Leiser Gedanke",
    text: "Sich sicher zu fühlen kann genauso aufregend sein wie Schmetterlinge.",
    caption: "Nur oft ein bisschen nachhaltiger.\n\n#choice #sicherheit #verbindung",
    background: "encounter",
  },
  {
    day: 25,
    weekday: "Donnerstag",
    theme: "Klarheit",
    purpose: "Dating-Realität",
    text: "Potenzial ist schön. Gegenseitigkeit ist schöner.",
    caption: "Achte nicht nur darauf, was sein könnte. Achte auch darauf, was wirklich da ist.\n\n#gegenseitigkeit #choice #datingklarheit",
    background: "midnight",
  },
  {
    day: 26,
    weekday: "Freitag",
    theme: "Mut",
    purpose: "Wochenend-Impuls",
    text: "Ein ehrliches ‚Ich würde dich gern wiedersehen‘ ist immer noch attraktiv.",
    caption: "Keine Taktik nötig.\n\n#datingmut #choice #ehrlichsein",
    background: "warmth",
  },
  {
    day: 27,
    weekday: "Samstag",
    theme: "Leichtigkeit",
    purpose: "Speicherbarer Satz",
    text: "Date-Idee: Jeder zeigt dem anderen einen Ort, an dem er gern Zeit verliert.",
    caption: "Zwei Orte. Zwei kleine Einblicke. Ein Date ohne Standardprogramm.\n\n#dateidee #choice #wochenende",
    background: "encounter",
  },
  {
    day: 28,
    weekday: "Sonntag",
    theme: "Reflexion",
    purpose: "Wochenabschluss",
    text: "Du suchst nicht irgendeine Antwort. Du suchst ein echtes Gegenüber.",
    caption: "Und dafür darfst du dir Zeit nehmen.\n\n#choice #echteverbindung #datingmitabsicht",
    background: "midnight",
  },
  {
    day: 29,
    weekday: "Montag",
    theme: "Haltung",
    purpose: "Choice-Gedanke",
    text: "Die richtige Verbindung fühlt sich nicht wie Auswahl an.\n\nSie fühlt sich wie Aufmerksamkeit an.",
    caption: "Nicht noch eine Möglichkeit. Sondern ein Mensch, dem du wirklich begegnest.\n\n#choice #bewusstdaten #echteverbindung",
    background: "encounter",
  },
  {
    day: 30,
    weekday: "Dienstag",
    theme: "Community",
    purpose: "Frage an die Community",
    text: "Welche Eigenschaft wird attraktiver, je länger du jemanden kennst?",
    caption: "Humor? Verlässlichkeit? Ruhe? Wir sind gespannt auf deine Antwort.\n\n#choicefrage #kennenlernen #dating",
    background: "warmth",
  },
  {
    day: 31,
    weekday: "Mittwoch",
    theme: "Nähe",
    purpose: "Leiser Gedanke",
    text: "Manchmal ist Verbundenheit nur das Gefühl, mit einem Gedanken nicht allein zu sein.",
    caption: "Ein ehrlicher Satz kann mehr Nähe schaffen als hundert perfekte Nachrichten.\n\n#choice #nähe #verbindung",
    background: "midnight",
  },
  {
    day: 32,
    weekday: "Donnerstag",
    theme: "Klarheit",
    purpose: "Dating-Realität",
    text: "Wer dich kennenlernen will, lässt dich nicht ständig über sein Interesse rätseln.",
    caption: "Interesse darf sich klar anfühlen. Du musst es nicht zwischen den Zeilen suchen.\n\n#datingklarheit #choice #gegenseitigkeit",
    background: "encounter",
  },
  {
    day: 33,
    weekday: "Freitag",
    theme: "Mut",
    purpose: "Wochenend-Impuls",
    text: "Schreib nicht die klügste Nachricht.\n\nSchreib die ehrlichste.",
    caption: "Die beste erste Nachricht muss nicht beeindrucken. Sie darf einfach ein echtes Gespräch beginnen.\n\n#choice #ehrlichschreiben #datingmut",
    background: "warmth",
  },
  {
    day: 34,
    weekday: "Samstag",
    theme: "Leichtigkeit",
    purpose: "Date-Idee",
    text: "Zwei Getränke. Ein langer Spaziergang. Kein fester Plan.",
    caption: "Manchmal braucht ein gutes Date weniger Programm und mehr Zeit.\n\n#dateidee #choice #wochenende",
    background: "midnight",
  },
  {
    day: 35,
    weekday: "Sonntag",
    theme: "Reflexion",
    purpose: "Wochenabschluss",
    text: "Vielleicht fehlt dir nicht die richtige Person.\n\nVielleicht nur die Ruhe, sie zu erkennen.",
    caption: "Nicht jede Verbindung ist sofort laut. Manche wird erst besonders, wenn du ihr Zeit gibst.\n\n#sonntagsgedanke #choice #bewusstdaten",
    background: "encounter",
  },
  {
    day: 36,
    weekday: "Montag",
    theme: "Haltung",
    purpose: "Choice-Gedanke",
    text: "Aufmerksamkeit ist eine Entscheidung.\n\nGenau wie weiterswipen.",
    caption: "Choice entscheidet sich für eine Begegnung, bevor die nächste beginnt.\n\n#choice #onematch #aufmerksamkeit",
    background: "midnight",
  },
  {
    day: 37,
    weekday: "Dienstag",
    theme: "Community",
    purpose: "Frage an die Community",
    text: "Welches Kompliment ist dir wirklich im Gedächtnis geblieben?",
    caption: "Vielleicht war es gar nicht das Offensichtliche. Erzähl es uns.\n\n#choicefrage #kompliment #kennenlernen",
    background: "warmth",
  },
  {
    day: 38,
    weekday: "Mittwoch",
    theme: "Nähe",
    purpose: "Leiser Gedanke",
    text: "Zuhören ist eine der leisesten Arten, jemanden zu wählen.",
    caption: "Nicht nur auf die nächste Antwort warten. Wirklich verstehen wollen.\n\n#choice #zuhören #echteverbindung",
    background: "encounter",
  },
  {
    day: 39,
    weekday: "Donnerstag",
    theme: "Klarheit",
    purpose: "Dating-Realität",
    text: "Ein fast passendes Match darf trotzdem ein Nein sein.",
    caption: "Fair zu entscheiden ist besser, als aus Unsicherheit weiterzumachen.\n\n#datingklarheit #choice #ehrlichkeit",
    background: "midnight",
  },
  {
    day: 40,
    weekday: "Freitag",
    theme: "Mut",
    purpose: "Wochenend-Impuls",
    text: "Du darfst zuerst sagen, dass dir etwas bedeutet.",
    caption: "Offenheit ist kein Verlust von Kontrolle. Sie ist eine Einladung zu Ehrlichkeit.\n\n#mut #choice #ehrlichsein",
    background: "warmth",
  },
  {
    day: 41,
    weekday: "Samstag",
    theme: "Leichtigkeit",
    purpose: "Speicherbarer Satz",
    text: "Gute Gespräche brauchen kein außergewöhnliches Thema. Nur echtes Interesse.",
    caption: "Die Person macht das Gespräch besonders, nicht die perfekte Frage.\n\n#choice #gespräche #kennenlernen",
    background: "encounter",
  },
  {
    day: 42,
    weekday: "Sonntag",
    theme: "Reflexion",
    purpose: "Wochenabschluss",
    text: "Nicht jede Verbindung beginnt mit Feuerwerk.\n\nManche beginnt mit Ruhe und bleibt.",
    caption: "Unterschätze nicht, was sich langsam und ehrlich entwickelt.\n\n#sonntagsgedanke #choice #verbindung",
    background: "midnight",
  },
];

export const BACKGROUND_LABELS: Record<InstagramBackground, string> = {
  encounter: "Schlicht Creme",
  midnight: "Schlicht Schwarz",
  warmth: "Schlicht Rosé",
};
